### ISSUE TITLE
some  little pbs in the new SRXSA-CLI.py

### ISSUE THREAD

**Issue by jg2944** [xmin0s/SRX-Session-Analyzer#3]
Hello Tim,
thanks for this new CLI based SRXSA-CLI.py;
I have just tried it and got some problems when running wih my Python 3.4;
I fixed them this way :  
some lines with : print("\n")*2  ==> I replaced them by print(("\n")*2) 
some lines with : print("-")*80 ==> I replaced them by print(("-")*80)
Line 461 : pp = int(j) ==> I put it in comment
Line 470 : pp = int(j) ==> I put it in comment

**Comment by Rochey** [comment]
Hello Tim,
I'm getting issues with the SRXSA-CLI.py as well - same as above. I added the print changes from above and it works a bit better.
I get an issue when using the --packets switch:

Traceback (most recent call last):
  File "SRXSA-CLI.py", line 475, in <module>
    analyze_session_table(sessiondata, numdisplayed)				
  File "SRXSA-CLI.py", line 461, in analyze_session_table
    pp = int(j)
UnboundLocalError: local variable 'j' referenced before assignment

and I get an issue when using the --bytes switch:
Traceback (most recent call last):
  File "SRXSA-CLI.py", line 475, in <module>
    analyze_session_table(sessiondata, numdisplayed)				
  File "SRXSA-CLI.py", line 470, in analyze_session_table
    pp = int(j)
UnboundLocalError: local variable 'j' referenced before assignment

all the other switches work as long as the print changes from the above comment are used.
